mode: balance
containers:
  - address: http://127.0.0.1:5700/
    username: qilinlin
    password: qi2814631
    cid: jHc7k6GI_8X4
    secret: g_5fEn-w2ZFLcegnW8ogOf2p
    weigth: 
    mode: parallel
    limit: 9999
  - address: http://35.220.196.236:5678/
    username: root
    password: root
    weigth: 
    mode: parallel
    limit: 9999
  - address: http://47.102.112.238:12311/ #99
    username: root
    password: root
    weigth: 1
    mode: balance
    limit: 40
  - address: http://47.102.112.238:12322/
    username: root
    password: root
    weigth: 1 
    mode: balance
    limit: 40
  - address: http://139.196.55.54:12311/ #17
    username: root
    password: root
    weigth: 1 
    mode: balance
    limit: 40
  - address: http://139.196.55.54:12322/
    username: root
    password: root
    weigth: 1 
    mode: balance
    limit: 40
AtTime: 3 #填写1-12之间的数  填错自负默认为10  10点容易出现高峰超时。
IsHelp: false  #填写true或者false  false
IsOldV4: true #填写true或者false  false是否新版或者旧版V4
Wskey: true #填空默认禁用wskey转换 需要的填true
IsAddFriend: true #填写true或者false  false
Lim: 3 #填写1-N 代表限制次数
tytnum: #填写1-N 代表推一推需要的互助值，默认为8
ApiToken: 23232323
theme: ./theme/admin.html
static: ./static
master:  qi2814631
database:  
qywx_key:
daily_push:
resident: jd_5df379cc9de74
user_agent:
telegram_bot_token: 
telegram_user_id: 
TGURL: #填写TG代理地址参考https://www.kejiwanjia.com/server/5221.html#3worker
qquid: 743173808
qqgid: 493514629
qbot_public_mode: true
default_priority:
no_ghproxy: false
daily_asset_push_cron: 30 21 * * *
repos:
  - git: https://github.com/shufflewzc/faker2.git
