mode: parallel
containers:
  - address:  http://104.199.180.88:5700/ #青龙2.2、青龙2.8、青龙2.9 v1v2v3v4v5访问地址（根据自己ip填）
    username: root  #青龙2.2、青龙2.8、青龙2.9 v1v2v3v4v5访问地址（根据自己ip填）
    password: root  #青龙2.2、青龙2.8、青龙2.9 v1v2v3v4v5访问地址（根据自己ip填）
    cid: dE5-QE6ozw5F  ## 用于配置2.9+的 应用，配置后，xdd不会顶掉青龙登录
    secret: lI2avmo4gvkDdizE1Hw4j-hc  ## 用于配置2.9+的 应用，配置后，xdd不会顶掉青龙登录
    weigth: 1
    mode: balance
    limit: 9999 #限制容器ck数目
  - address:  http://139.196.55.54:5700/ #青龙2.2、青龙2.8、青龙2.9 v1v2v3v4v5访问地址（根据自己ip填）
    username: root  #青龙2.2、青龙2.8、青龙2.9 v1v2v3v4v5访问地址（根据自己ip填）
    password: root  #青龙2.2、青龙2.8、青龙2.9 v1v2v3v4v5访问地址（根据自己ip填）
    cid: MD2SPyN_KgDP  ## 用于配置2.9+的 应用，配置后，xdd不会顶掉青龙登录
    secret: wZbzhJASHCMbSgr3oa1-Clhi  ## 用于配置2.9+的 应用，配置后，xdd不会顶掉青龙登录
    weigth: 1
    mode: balance
    limit: 40 #限制容器ck数目
  - address:  http://47.102.112.238:5700/ #青龙2.2、青龙2.8、青龙2.9 v1v2v3v4v5访问地址（根据自己ip填）
    username: root  #青龙2.2、青龙2.8、青龙2.9 v1v2v3v4v5访问地址（根据自己ip填）
    password: root  #青龙2.2、青龙2.8、青龙2.9 v1v2v3v4v5访问地址（根据自己ip填）
    cid: G-vZqgVZ6sey  ## 用于配置2.9+的 应用，配置后，xdd不会顶掉青龙登录
    secret: _4pQreVD4_7q5DcQka26gcEV  ## 用于配置2.9+的 应用，配置后，xdd不会顶掉青龙登录
    weigth: 1
    mode: balance
    limit: 40 #限制容器ck数目
  - address:  http://ql.tingfengzhe.asia:81/ #青龙2.2、青龙2.8、青龙2.9 v1v2v3v4v5访问地址（根据自己ip填）
    username: root  #青龙2.2、青龙2.8、青龙2.9 v1v2v3v4v5访问地址（根据自己ip填）
    password: root  #青龙2.2、青龙2.8、青龙2.9 v1v2v3v4v5访问地址（根据自己ip填）
    cid: 2xgmYGuN-8R9  ## 用于配置2.9+的 应用，配置后，xdd不会顶掉青龙登录
    secret: RjTH9B-xLeGzhivuc3Ob_euu  ## 用于配置2.9+的 应用，配置后，xdd不会顶掉青龙登录
    weigth: 
    mode: parallel
    limit: 9999 #限制容器ck数目
AtTime: 6 #填写1-12之间的数  填错自负默认为10  10点容易出现高峰超时。
IsHelp: false  #填写true或者false  false
IsOldV4: true #填写true或者false  false是否新版或者旧版V4
Wskey: # 填空默认禁用wskey转换 需要的填true
IsAddFriend: false #填写true或者false  false
Lim: 3 #填写1-N 代表限制次数
Tyt: #填写1-N 代表推一推需要的互助值，默认为8
Later: #延时防止黑IP自己设置 默认60 不怕黑的改为1即可 单位是秒
theme: ./theme/admin.html
static: ./static
master: qi2814631
database:  
qywx_key:
daily_push:
resident: jd_5df379cc9de74&jd_tkiWtojFNzYM&jd_6a53ed5da4327&jd_71f75a8d31877
user_agent:
telegram_bot_token:
telegram_user_id:
TGURL: #填写TG代理地址参考https://www.kejiwanjia.com/server/5221.html#3worker
qquid: 743173808
qqgid: 493514629
qbot_public_mode: false
default_priority:
no_ghproxy: false
daily_asset_push_cron:
#repos:
  #- git: https://github.com/shufflewzc/faker2.git